# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df0ba1fc544cd19e8f7f9139afddd205580ba4854856bf51ef114904fc259653b46d6b429d0646ffda197bdf521c16f113eb5d031b4dfa87e1b8a399a07e14da

test:
  secret_key_base: c2dd922baea92d6f6077090d264c1fcb1dfd438af21cc44cf4c50dfdef68a32fd47cf30470db67859117368250d79627f8882b5ba83b063fc8a8bc12cabd2ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
